server:
  port: 64101
spring:
  datasource:
    uri: jdbc.mysql://localhost:3306/soulmateDB
    username: root
    password: Root@5222
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
