server:
  port: 64100
spring:
  application:
    name: userService
  datasource:
    uri: jdbc.mysql://localhost:3306/soulmateDB
    username: root
    password: Root@5222
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect








server.port=64100
spring.datasource.url=jdbc:mysql://localhost:3306/soulmateDB
spring.datasource.username=root
spring.datasource.password=Root@5222
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.application.name=userService